spring.application.name=Storage Service

server.port=8083

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/storage
spring.datasource.username=storage
spring.datasource.password=storage

spring.jpa.hibernate.ddl-auto=update

# Google Cloud Storage
spring.cloud.gcp.project-id=your-gcp-project-id
spring.cloud.gcp.credentials.location=classpath:gcp-service-account.json

# Storage Service Settings
storage.bucket-name=audio-video-converter-files
storage.base-path=uploads